# Java Gradle CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-java/
version: '2.1'
#orbs:
#  gradle: circleci/gradle@5.6.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
#workflows:
#  gerrit-ci-pipeline:
jobs:
  build:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      # specify the version you desire here
      - image: circleci/openjdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: gradle build
          command: ./gradlew clean jar
#           /home/circleci/repo/build/libs/circleci-jfrog-test-1.0.jar

      - save_cache:
          paths:
            - ~/.gradle
            - /home/circleci/repo/build/libs
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests.
      - run: gradle test
  upload_to_jfrog:
    docker:
      - image: circleci/openjdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install jFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
      - run:
          name: jar preparation
          command: ./gradlew clean jar
      - run:
          name: Push to Artifactory
          command: |
            ls -al /home/circleci/repo/build/libs/circleci-jfrog-test-1.0.jar 
            ./jfrog config add artifactory-server --artifactory-url="$ARTIFACTORY_URL" --user="$ARTIFACTORY_USER" --password=$ARTIFACTORY_PASSWORD --interactive=false
#            echo "Config is successful!"
#            ./jfrog rt u /home/circleci/repo/build/libs/circleci-jfrog-test-1.0.jar tiger-prod --build-name=tiger-prod --build-number=$CIRCLE_BUILD_NUM
#            echo "u is successful"
#            ./jfrog rt bce tiger-prod $CIRCLE_BUILD_NUM  # collects all environment variables on the agent
#            echo "bce is successful"
#            ./jfrog rt bp tiger-prod $CIRCLE_BUILD_NUM  # attaches ^^ to the build in artifactory
#            echo "bp is successful"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - upload_to_jfrog:
          requires:
            - build
          filters:
            branches:
              only:
                main
  build_only:
    jobs:
      - build
